### ISSUE TITLE
No ping and pong message handlers found in your sample....

### ISSUE THREAD

**Issue by jeven2016** [luis-moral/sample-webflux-websocket-netty#1]
this is a very good sample, but no ping and pong message handlers found in your sample....
Could you provide such implementation?

Thanks

**Comment by luis-moral** [comment]
Hello,

The ping pong is implemented in ServerLogic and ClientLogic doLogic() method, is that what you looking for?

[ServerLogic](src/main/java/sample/webflux/websocket/netty/logic/ServerLogic.java)

[ClientLogic](src/main/java/sample/webflux/websocket/netty/logic/ClientLogic.java)

**Comment by jeven2016** [comment]
Thanks so much, I'm implementing the similar microservice and your project is very very helpful for understanding the websocket with webflux, I can't find anyother projects better then yours.

 : )

Thanks
