### ISSUE TITLE
STOMP

### ISSUE THREAD

**Issue by co5dt** [luis-moral/sample-webflux-websocket-netty#2]
Great help, thanks! 
Do you happen to have any information on how to do STOMP over WS using Netty Client?

**Comment by luis-moral** [comment]
Hello, sorry no idea, havent used STOMP yet :(

**Comment by matthewshine** [comment]
thanks for sharing!
is this avaiable on distributed systems? if there are 3 servers running websocket on them.
3 users connect to different server , could they send message to each other?

**Comment by luis-moral** [comment]
Hello,

Sorry this would not be possible with this example, you would have to implement or use some synchronization mechanism.

**Comment by matthewshine** [comment]
thanks for replying,would u share some keyswords for searching in google?
